In [15]:
import torch
import numpy as np

In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = torch.arange(6,device=device).reshape(2,3)
print(x.device)
x

cpu


tensor([[0, 1, 2],
        [3, 4, 5]])

In [12]:
y = torch.randint(5,11,(2,3),device=device)
y

tensor([[7, 7, 8],
        [6, 8, 5]])

In [14]:
z = x+y
z.shape

torch.Size([2, 3])

### Creating Tensors

In [16]:
torch.tensor([2,4,1])  # by list

tensor([2, 4, 1])

In [20]:
torch.tensor(np.random.randn(3))  # from numpy ndarray

tensor([-0.5009,  0.0458, -0.6733], dtype=torch.float64)

In [29]:
torch.empty(4)  # tensor with unknown values

tensor([ 7.7142e-39,  1.0010e-38, -3.4582e+34,  4.5916e-41])

In [26]:
x=torch.zeros(2,4)   # zeros with given shape
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
torch.ones_like(x)  # ones using shape of some other tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
torch.rand(2,3)  # tensor with numbers from normal distribution

tensor([[0.3545, 0.9768, 0.4817],
        [0.3853, 0.1201, 0.7042]])

In [31]:
torch.randint(1,6,(2,4))  # tensor with random int

tensor([[4, 3, 2, 1],
        [4, 1, 3, 5]])

In [34]:
torch.zeros(3,device=device) # specify the device as well

tensor([0., 0., 0.])

In [37]:
x = torch.linspace(0,1,16).reshape(4,4)
x

tensor([[0.0000, 0.0667, 0.1333, 0.2000],
        [0.2667, 0.3333, 0.4000, 0.4667],
        [0.5333, 0.6000, 0.6667, 0.7333],
        [0.8000, 0.8667, 0.9333, 1.0000]])

In [44]:
# access multiple attributes of the tensor

print(f'shape : {x.shape}')
print(f'device : {x.device}')
print(f'dtype : {x.dtype}')
print(f'ndim : {x.ndim}')
print(f'requires grad : {x.requires_grad}')

shape : torch.Size([4, 4])
device : cpu
dtype : torch.float32
ndim : 2
requires grad : False


In [47]:
# cast from one dtype to another
w = torch.tensor([-9,4,1],dtype=torch.float32)
w.int() # w is still a float

tensor([-9,  4,  1], dtype=torch.int32)

In [49]:
x = torch.arange(0,10,(2,5))

TypeError: arange() received an invalid combination of arguments - got (int, int, tuple), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [51]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x.view(2,5)  # prefer view over reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])