In [1]:
import torch
import numpy as np

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = torch.arange(6,device=device).reshape(2,3)
print(x.device)
x

cpu


tensor([[0, 1, 2],
        [3, 4, 5]])

In [3]:
y = torch.randint(5,11,(2,3),device=device)
y

tensor([[ 5,  5,  5],
        [ 6,  9, 10]])

In [4]:
z = x+y
z.shape

torch.Size([2, 3])

### Creating Tensors

In [5]:
torch.tensor([2,4,1])  # by list

tensor([2, 4, 1])

In [6]:
torch.tensor(np.random.randn(3))  # from numpy ndarray

tensor([ 0.6308, -1.5909,  1.3682], dtype=torch.float64)

In [7]:
torch.empty(4)  # tensor with unknown values

tensor([2.3964e-06, 4.5814e-41, 2.1260e-09, 4.5814e-41])

In [8]:
x=torch.zeros(2,4)   # zeros with given shape
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
torch.ones_like(x)  # ones using shape of some other tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.rand(2,3)  # tensor with numbers from normal distribution

tensor([[0.7951, 0.1319, 0.9668],
        [0.3288, 0.5541, 0.6015]])

In [11]:
torch.randint(1,6,(2,4))  # tensor with random int

tensor([[1, 1, 1, 2],
        [4, 1, 5, 4]])

In [12]:
torch.zeros(3,device=device) # specify the device as well

tensor([0., 0., 0.])

In [13]:
x = torch.linspace(0,1,16).reshape(4,4)
x

tensor([[0.0000, 0.0667, 0.1333, 0.2000],
        [0.2667, 0.3333, 0.4000, 0.4667],
        [0.5333, 0.6000, 0.6667, 0.7333],
        [0.8000, 0.8667, 0.9333, 1.0000]])

In [14]:
# access multiple attributes of the tensor

print(f'shape : {x.shape}')
print(f'device : {x.device}')
print(f'dtype : {x.dtype}')
print(f'ndim : {x.ndim}')
print(f'requires grad : {x.requires_grad}')

shape : torch.Size([4, 4])
device : cpu
dtype : torch.float32
ndim : 2
requires grad : False


In [15]:
# cast from one dtype to another
w = torch.tensor([-9,4,1],dtype=torch.float32)
w.int() # w is still a float

tensor([-9,  4,  1], dtype=torch.int32)

In [17]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.view(2,5)  # prefer view over reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
# combine or split tensors example
x = torch.arange(0,10).reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
# combine tensors
y = torch.stack((x,x))
y

tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]])

In [31]:
x.unbind(dim=1) # split tensor

(tensor([0, 5]),
 tensor([1, 6]),
 tensor([2, 7]),
 tensor([3, 8]),
 tensor([4, 9]))

In [33]:
x.unbind(dim=0) # split along different dimension

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]))

In [38]:
# squeeze method

# removes all dim of size 1
x = torch.zeros(2, 1, 2, 1, 2)
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

### Pointwise Operations

These operations are applied individually on all elements of a tensor

In [39]:
x = torch.randn(5)
x

tensor([ 0.0113, -0.0994,  0.7990,  1.2700,  0.9998])

In [41]:
x.floor()

tensor([ 0., -1.,  0.,  1.,  0.])

In [42]:
x.sin()

tensor([ 0.0113, -0.0992,  0.7167,  0.9551,  0.8414])

In [46]:
x.add(1)

tensor([1.0113, 0.9006, 1.7990, 2.2700, 1.9998])

In [48]:
x  # original tensor remains the same by default

tensor([ 0.0113, -0.0994,  0.7990,  1.2700,  0.9998])

### Reduction Operations

These operations reduce the dimensionality of the a tensor.

In [54]:
x = torch.randint(0,10,(1,10))
x

tensor([[8, 9, 1, 6, 7, 4, 8, 6, 6, 5]])

In [ ]:
torch.argmax(x,)